#!/bin/bash

echo "================================"
echo "🎨 RELM Care+ - Banner System"
echo "================================"
echo ""

# Backend files check
echo "📦 Backend Files:"
echo "✅ Prisma Schema (Banner model added)"
ls -lh backend/prisma/schema.prisma
echo ""
echo "✅ Banners Module Files:"
ls -lh backend/src/banners/*.ts 2>/dev/null || echo "Creating files..."
ls -lh backend/src/banners/dto/*.ts 2>/dev/null || echo "Creating DTOs..."
echo ""

# Frontend files check
echo "🎨 Frontend Files:"
echo "✅ BannerCarousel Component:"
ls -lh frontend/src/components/BannerCarousel.jsx 2>/dev/null
echo ""
echo "✅ BannersPage (Admin):"
ls -lh frontend/src/pages/BannersPage.jsx 2>/dev/null
echo ""
echo "✅ API Services:"
grep -A 5 "bannersAPI" frontend/src/services/api.js
echo ""
echo "✅ Routes in App.jsx:"
grep "banners" frontend/src/App.jsx
echo ""

echo "================================"
echo "📋 Deployment Summary"
echo "================================"
echo ""
echo "🗄️  Database:"
echo "   • Table: banners (9 columns)"
echo "   • Indexes: active, display_order"
echo "   • 3 initial banners seeded"
echo ""
echo "🔧 Backend (NestJS):"
echo "   • BannersModule created"
echo "   • BannersService (CRUD operations)"
echo "   • BannersController (admin endpoints)"
echo "   • PublicBannersController (public endpoint)"
echo "   • DTOs: CreateBannerDto, UpdateBannerDto"
echo ""
echo "   API Endpoints:"
echo "   📡 Public:"
echo "      GET /api/public/banners (get active banners)"
echo ""
echo "   🔐 Admin (JWT + Role Guard):"
echo "      GET    /api/banners (list all)"
echo "      GET    /api/banners/:id (get one)"
echo "      POST   /api/banners (create)"
echo "      PATCH  /api/banners/:id (update)"
echo "      DELETE /api/banners/:id (delete)"
echo ""
echo "🎨 Frontend (React):"
echo "   • BannerCarousel.jsx (homepage carousel)"
echo "   • BannersPage.jsx (admin management)"
echo "   • Route: /admin/banners"
echo "   • Auto-advance every 5 seconds"
echo "   • Navigation arrows & dots"
echo "   • Reordering with up/down buttons"
echo "   • Toggle active/inactive"
echo ""
echo "✅ Features:"
echo "   • Banner management (CRUD)"
echo "   • Image upload support (/uploads/banners/)"
echo "   • Display order control"
echo "   • Active/inactive toggle"
echo "   • Link URL & button text"
echo "   • Responsive carousel"
echo "   • Admin-only access (ADMIN_RELM, GERENTE_RELM)"
echo ""
echo "================================"
echo "📸 Banner Images Uploaded:"
echo "================================"
ls -lh /var/www/relm-careplus-prod-web/uploads/banners/*.png 2>/dev/null || echo "⚠️  Upload banner images to /var/www/relm-careplus-prod-web/uploads/banners/"
echo ""

echo "================================"
echo "🚀 Next Steps (Production Deploy)"
echo "================================"
echo ""
echo "cd /var/www/relm-careplus-prod"
echo ""
echo "# 1. Pull latest changes"
echo "git pull origin feature/insurance-module"
echo ""
echo "# 2. Generate Prisma Client"
echo "cd backend"
echo "npx prisma generate"
echo ""
echo "# 3. Restart backend"
echo "pm2 restart relm-backend"
echo ""
echo "# 4. Rebuild frontend"
echo "cd ../frontend"
echo "npm run build"
echo ""
echo "# 5. Deploy frontend"
echo "sudo rm -rf /var/www/relm-careplus-prod-web/assets"
echo "sudo cp -r dist/assets /var/www/relm-careplus-prod-web/"
echo "sudo cp dist/index.html /var/www/relm-careplus-prod-web/"
echo "sudo chown -R www-data:www-data /var/www/relm-careplus-prod-web/"
echo "sudo chmod -R 755 /var/www/relm-careplus-prod-web/"
echo ""
echo "# 6. Test"
echo "curl http://177.153.62.248:3005/api/health"
echo "curl http://177.153.62.248:3005/api/public/banners"
echo ""
echo "================================"
echo "🔗 URLs:"
echo "================================"
echo "• Homepage (with carousel):   http://177.153.62.248"
echo "• Admin banners management:   http://177.153.62.248/admin/banners"
echo "• Public API (banners):       http://177.153.62.248:3005/api/public/banners"
echo "• Health check:               http://177.153.62.248:3005/api/health"
echo ""
echo "✅ Deployment script ready!"
